# Generated by Django 6.0.5 on 2026-05-26 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='')),
                ('is_purchased', models.BooleanField(default=False)),
                ('purchaseId', models.CharField(default='')),
            ],
        ),
    ]
