# Generated by Django 6.0.5 on 2026-05-26 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='username',
            new_name='accountid',
        ),
    ]
