# Generated by Django 6.0.5 on 2026-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_status_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='name',
        ),
    ]
