# Generated by Django 6.0.5 on 2026-05-26 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_status_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='accountid',
            new_name='username',
        ),
    ]
