# Generated by Django 6.0.5 on 2026-05-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='tags',
            field=models.JSONField(default=list),
        ),
    ]
