# Generated by Django 6.0.5 on 2026-05-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_status_is_purchased_status_purchasedgames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='vesion',
            new_name='version',
        ),
    ]
