# Generated by Django 4.2 on 2026-05-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_vesion_game_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='discription',
            new_name='description',
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='purchaseId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
