# Generated by Django 4.2 on 2026-05-27 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_discription_game_description_alter_game_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='description',
        ),
        migrations.AddField(
            model_name='game',
            name='discription',
            field=models.TextField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='status',
            name='purchaseId',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='status',
            name='username',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
