# Generated by Django 6.0.5 on 2026-05-26 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_rename_accountid_status_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='')),
                ('short_description', models.CharField(default='')),
                ('tags', models.CharField(default='')),
                ('discription', models.TextField(default='')),
                ('attrs', models.JSONField(default=list)),
                ('price', models.IntegerField(default=0)),
                ('image', models.CharField(default='')),
            ],
        ),
    ]
