# Generated by Django 6.0.5 on 2026-05-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_game_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='vesion',
            field=models.CharField(default=''),
        ),
    ]
