# Generated by Django 6.0.5 on 2026-05-26 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_game_vesion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
