# Generated by Django 6.0.5 on 2026-05-26 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_game_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='is_purchased',
        ),
        migrations.AddField(
            model_name='status',
            name='purchasedGames',
            field=models.JSONField(default=list),
        ),
    ]
