# Generated by Django 4.2 on 2026-05-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_discription_game_description_alter_game_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='status',
            name='purchaseId',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='status',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
