# Generated by Django 4.2 on 2026-05-28 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_game_name_alter_game_short_description_and_more'),
        ('home', '0013_remove_game_description_game_discription_and_more'),
    ]

    operations = [
    ]
