# Generated by Django 4.2 on 2026-05-28 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_merge_20260528_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='game',
            name='version',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='status',
            name='purchaseId',
            field=models.CharField(default='', max_length=9999),
        ),
        migrations.AlterField(
            model_name='status',
            name='username',
            field=models.CharField(default='', max_length=9999),
        ),
    ]
