# Generated by Django 4.2 on 2026-05-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_alter_game_name_alter_game_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='download_link',
            field=models.TextField(default=''),
        ),
    ]
